token:
  ID: easter2016
  Title: Easter Egg
  BoundPrefix: "Bound to: &6"
  Description:
  - Collect Easter Eggs and trade
  - them with the Easter Bunny at
  - spawn for fantastic Easter
  - prizes!
